### PR TITLE
New functionalities

### PR DESCRIPTION
**Pull request by teunis90**
Hi friends at NedWalletOSS,

We were inspired by the work you have put in VersionAlchemy and have extended the library with new functionalities.

What we have done:
- Support for Python3
- Restore records: `restore(va_id)`
- List history: `va_list()`
- Get historic `va_get()`
- Diff records `va_diff(va_id, va_id)`
- Get all changes `va_diff_all()`
- Get all records: `va_get_all()`

We have extensively tested those functionalities and would like to see them in the official repository. Can you create a new PIP package version after accepting PR?

### CODE REVIEW

**Comment by kushan-gunasekera** [comment]
Hello @teunis90 ,  I forked this branch and did some changes. But I cannot make a pull request to **Nextpertise:master**. See this attachment --> [image](https://i.imgur.com/5oOub9z.png)

**Comment by luislew** [comment]
@kushan-gunasekera sorry, we didn't see your PR until just now... We're adding Python 3 support right now (see #21)

**Comment by teunis90** [comment]
Hi @luislew, thanks for your answer. What about the other features? If we need to change something, please let us know.

**Comment by luislew** [comment]
@teunis90 we can definitely work with you to polish up the PR and ship these new features, or if you'd prefer we can take over this work and follow up when it's shipped. either way, i'd estimate a couple of weeks before we can get this in + new release. FYI this would go out as `1.1.0`, since it will be new, non-breaking functionality.

**Comment by luislew** [comment]
@teunis90 quick update, a Python 3 compatible release was just made under `1.0.0`: https://pypi.org/project/versionalchemy/1.0.0/

**Comment by teunis90** [comment]
@luislew Thanks or the update, feel free to take over. We are swamped with work here :)

**Comment by GilUpstream** [comment]
Closing due to inactivity and prior to archiving this project. Please feel free to fork the project if needed.

**Comment by GilUpstream** [comment]
Closing due to inactivity and prior to archiving this project. Please feel free to fork the project if needed.

**Pull request closed without merging**
